name: Alert Cron
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel alert endpoint
        env:
          URL: ${{ secrets.VERCEL_ALERT_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl -fsS -H "x-cron-secret: $CRON_SECRET" "$URL" || exit 1
